In [6]:
import pandas as pd
import numpy as np
import pyarrow.dataset as ds
import pyarrow.parquet as pq

In [17]:
pq.ParquetDataset("embeddings/age/preprocessed_emb/train").schema.names

['client_id',
 'age',
 'trans_date',
 'small_group',
 'amount_rur',
 '_seq_len',
 'shifts',
 'target__reg_amount__local__mse',
 'target__age__global__F1',
 'target__forecast__local__mse',
 'target__forecast__local_AUCROC',
 'debug_f',
 'shard',
 'embeddings']

In [14]:
df = pd.read_parquet("embeddings/age/preprocessed/train")

In [15]:
df["embeddings"] = df["shifts"].map(lambda x: np.random.randn(len(x), 512).tolist())
df = df.rename(
    columns={
        "post_reg_target": "target__reg_amount__local__mse",
        "post_target": "target__age__global__F1",
        "post_forecast_target": "target__forecast__local__mse",
        "post_anomaly_target": "target__forecast__local_AUCROC"
    }
)

In [16]:
df.to_parquet("embeddings/age/preprocessed_emb/train")

In [9]:
df

,client_id,age,trans_date,small_group,amount_rur,_seq_len,shifts,post_reg_target,post_target,post_forecast_target,post_anomaly_target,debug_f,shard
0,4,1,"[0, 2, 3, 4, 6, 6, 8, 9, 9, 10, 10, 11, 11, 12...","[1, 3, 1, 1, 5, 1, 1, 1, 13, 1, 4, 12, 1, 1, 1...","[10.208999633789062, 27.70599937438965, 13.024...",720,[657],[6.714134112856427],[1],[0.6931471805599453],[0],[664],0
20,32,3,"[1, 4, 7, 7, 7, 7, 8, 9, 10, 11, 11, 12, 12, 1...","[6, 25, 16, 1, 4, 7, 1, 1, 1, 2, 62, 4, 8, 6, ...","[6.86899995803833, 113.11499786376953, 3.75500...",1035,[962],[7.712540424181622],[3],[1.6094379124341003],[0],[692],0
40,58,0,"[9, 10, 11, 11, 14, 14, 15, 16, 18, 18, 19, 20...","[3, 8, 9, 1, 3, 2, 9, 9, 9, 1, 1, 9, 1, 1, 8, ...","[1.2359999418258667, 1.725000023841858, 4.5789...",890,[774],[6.976667341425622],[0],[0.6931471805599453],[0],[638],0
60,88,0,"[2, 2, 3, 3, 4, 4, 4, 5, 5, 5, 5, 6, 6, 7, 9, ...","[2, 7, 3, 2, 63, 80, 1, 10, 5, 2, 1, 17, 1, 3,...","[21.908000946044922, 69.3280029296875, 13.7379...",939,[880],[6.028928909896153],[0],[0.6931471805599453],[0],[663],0
80,116,0,"[0, 1, 2, 3, 3, 4, 4, 4, 5, 5, 5, 5, 6, 6, 7, ...","[51, 8, 1, 51, 2, 8, 1, 90, 8, 1, 17, 10, 17, ...","[16.83799934387207, 5.677999973297119, 21.5170...",1100,[963],[7.427268456288772],[0],[0.6931471805599453],[0],[661],0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29905,49850,1,"[1, 2, 2, 4, 4, 5, 6, 6, 7, 7, 8, 9, 9, 10, 10...","[3, 14, 95, 3, 72, 1, 17, 1, 5, 1, 3, 2, 3, 3,...","[138.00900268554688, 13.692999839782715, 1689....",1117,[1005],[7.660247670366146],[1],[1.0986122886681096],[0],[675],9
29925,49881,1,"[6, 9, 9, 11, 11, 11, 19, 19, 20, 20, 20, 21, ...","[2, 16, 4, 4, 6, 1, 4, 1, 20, 1, 5, 3, 1, 55, ...","[40.483001708984375, 69.26300048828125, 127.95...",717,[612],[7.8636251193380655],[1],[1.791759469228055],[0],[684],9
29945,49913,1,"[1, 1, 7, 9, 12, 12, 13, 15, 16, 16, 22, 23, 2...","[3, 31, 3, 30, 6, 7, 3, 5, 1, 34, 3, 15, 10, 1...","[9.159000396728516, 30.14699935913086, 12.9379...",742,[656],[6.2869138792449935],[1],[0.6931471805599453],[0],[647],9
29965,49947,0,"[0, 1, 1, 2, 2, 2, 7, 7, 7, 7, 8, 8, 8, 8, 8, ...","[1, 2, 19, 6, 45, 32, 2, 1, 28, 32, 4, 31, 17,...","[18.243000030517578, 12.680000305175781, 881.1...",792,[684],[7.793939309712851],[0],[0.6931471805599453],[0],[653],9
29985,49978,3,"[0, 4, 5, 5, 6, 6, 7, 8, 10, 11, 11, 12, 17, 1...","[3, 3, 53, 1, 72, 6, 24, 6, 9, 3, 40, 4, 1, 3,...","[22.898000717163086, 6.468999862670898, 30.594...",960,[803],[7.27146044859954],[3],[0.6931471805599453],[1],[654],9

In [12]:
df.iloc[0]["trans_date"][df.iloc[0]["shifts"][-1]]

574

In [18]:
df = pd.read_parquet("embeddings/age/preprocessed_emb/train")

In [19]:
df

,client_id,age,trans_date,small_group,amount_rur,_seq_len,shifts,target__reg_amount__local__mse,target__age__global__F1,target__forecast__local__mse,target__forecast__local_AUCROC,debug_f,shard,embeddings
0,4,1,"[0, 2, 3, 4, 6, 6, 8, 9, 9, 10, 10, 11, 11, 12...","[1, 3, 1, 1, 5, 1, 1, 1, 13, 1, 4, 12, 1, 1, 1...","[10.208999633789062, 27.70599937438965, 13.024...",629,"[22, 87, 150, 280, 303, 447, 490, 563, 566]","[6.583873851699495, 6.931505989559522, 6.62177...","[1, 1, 1, 1, 1, 1, 1, 1, 1]","[0.6931471805599453, 1.3862943611198906, 0.693...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[23, 90, 150, 290, 312, 461, 505, 570, 574]",0,"[[-1.075549907642658, -0.12425266767506796, -0..."
1,32,3,"[1, 4, 7, 7, 7, 7, 8, 9, 10, 11, 11, 12, 12, 1...","[6, 25, 16, 1, 4, 7, 1, 1, 1, 2, 62, 4, 8, 6, ...","[6.86899995803833, 113.11499786376953, 3.75500...",856,"[280, 291, 310, 520, 522, 541, 611, 657, 700]","[7.8964541180632635, 7.621126571456567, 7.9511...","[3, 3, 3, 3, 3, 3, 3, 3, 3]","[1.0986122886681096, 1.3862943611198906, 0.693...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[241, 248, 257, 412, 414, 423, 463, 498, 519]",0,"[[0.9651524596286758, -0.28087298276488215, -0..."
2,58,0,"[9, 10, 11, 11, 14, 14, 15, 16, 18, 18, 19, 20...","[3, 8, 9, 1, 3, 2, 9, 9, 9, 1, 1, 9, 1, 1, 8, ...","[1.2359999418258667, 1.725000023841858, 4.5789...",773,"[121, 130, 132, 147, 182, 311, 464, 594, 724]","[6.1335672262302685, 5.99881744495336, 5.91041...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.6931471805599453, 0.6931471805599453, 0.693...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[91, 101, 103, 114, 186, 284, 402, 501, 589]",0,"[[-1.8662479227306852, 0.29439089318348144, -0..."
3,88,0,"[2, 2, 3, 3, 4, 4, 4, 5, 5, 5, 5, 6, 6, 7, 9, ...","[2, 7, 3, 2, 63, 80, 1, 10, 5, 2, 1, 17, 1, 3,...","[21.908000946044922, 69.3280029296875, 13.7379...",862,"[136, 257, 261, 287, 295, 381, 572, 675, 685]","[8.385900186376585, 7.797837148869783, 7.83726...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.6931471805599453, 0.6931471805599453, 1.098...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[100, 180, 183, 199, 202, 262, 446, 510, 515]",0,"[[-1.9037014797377143, -2.256779138091125, 0.5..."
4,116,0,"[0, 1, 2, 3, 3, 4, 4, 4, 5, 5, 5, 5, 6, 6, 7, ...","[51, 8, 1, 51, 2, 8, 1, 90, 8, 1, 17, 10, 17, ...","[16.83799934387207, 5.677999973297119, 21.5170...",899,"[374, 606, 613, 627, 649, 697, 731, 780, 786]","[6.738822876472174, 7.933068657647543, 7.92708...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.6931471805599453, 0.6931471805599453, 0.693...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[298, 464, 471, 479, 490, 526, 544, 568, 572]",0,"[[-1.0076407134161913, 0.9893582900378854, 0.5..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,49857,0,"[1, 1, 2, 4, 8, 9, 9, 10, 11, 11, 12, 12, 13, ...","[1, 42, 95, 3, 13, 51, 13, 1, 10, 1, 1, 2, 9, ...","[7.072999954223633, 155.25900268554688, 86.254...",651,"[18, 41, 112, 168, 173, 261, 312, 553, 596]","[6.691893890199913, 5.576043782900024, 6.98085...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.6931471805599453, 0.6931471805599453, 0.693...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[17, 75, 203, 239, 244, 329, 371, 579, 597]",9,"[[1.3808985884748555, 0.029530861734682008, -0..."
29996,49888,0,"[1, 1, 2, 10, 19, 19, 20, 22, 23, 23, 24, 26, ...","[4, 2, 8, 8, 50, 6, 6, 95, 14, 1, 6, 14, 48, 3...","[32.86399841308594, 35.492000579833984, 25.388...",798,"[40, 141, 191, 228, 304, 343, 419, 517, 654]","[6.53435554279494, 8.101333754178727, 7.599668...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.6931471805599453, 0.6931471805599453, 1.098...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[110, 266, 294, 319, 373, 393, 432, 498, 572]",9,"[[0.510347667412527, -1.2416320431424617, 0.18..."
29997,49921,0,"[1, 9, 9, 17, 17, 17, 21, 23, 23, 30, 30, 30, ...","[2, 14, 1, 15, 25, 3, 2, 19, 3, 14, 3, 15, 12,...","[32.652000427246094, 2.7019999027252197, 42.56...",656,"[67, 92, 99, 223, 251, 274, 285, 556, 588]","[7.036232035842445, 7.62223919313787, 7.789536...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.6931471805599453, 0.6931471805599453, 1.098...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[102, 141, 145, 238, 267, 292, 302, 526, 561]",9,"[[1.7486742275572587, 0.892690415005009, -0.69..."
29998,49955,0,"[24, 25, 26, 26, 29, 29, 29, 30, 33, 33, 34, 3...","[9, 12, 12, 17, 9, 1, 2, 9, 10, 12, 2, 23, 43,...","[3.2049999237060547, 17.996999740600586, 13.47...",698,"[62, 84, 135, 239, 250, 293, 409, 411, 517]","[6.160705081727795, 5.838036523866921, 4.36355...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.6931471805599453, 1.6094379124341003, 0.693...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[94, 114, 159, 271, 286, 323, 444, 445, 520]",9,"[[0.16833714599339977, 0.932746124146842, -1.3..."
29999,49983,3,"[0, 1, 2, 5, 8, 8, 9, 9, 9, 10, 10, 10, 10, 12...","[3, 7, 1, 3, 1, 3, 3, 72, 1, 3, 36, 19, 34, 3,...","[15.095000267028809, 103.49600219726562, 125.4...",769,"[3, 139, 222, 304, 322, 348, 396, 566, 598]","[7.293661679685427, 6.779023791145487, 7.93039...","[3, 3, 3, 3, 3, 3, 3, 3, 3]","[0.6931471805599453, 0.6931471805599453, 1.609...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[5, 123, 218, 275, 284, 298, 325, 501, 537]",9,"[[-1.8124277012900598, -0.003440762037853717, ..."